//! Shared host-side helpers for working with Project Oberon artifacts.
//!
//! The tools in this crate are separate `src/bin/` programs and deliberately
//! share little, but a few low-level Oberon rules must agree across them. Those
//! live here so there is a single source of truth (and one set of tests) rather
//! than a copy per binary that can quietly drift.

/// Whether byte `ch` is legal at 0-based position `i` of a Project Oberon file
/// name: a leading ASCII letter, then letters, digits, or `.` (the `FileDir.Mod`
/// rule, mirrored by `norebo.c`'s `files_check_name`).
///
/// This is the per-character predicate only; callers layer their own length and
/// termination rules on top (a NUL-terminated guest buffer, a fixed-width
/// on-disk field), so it intentionally says nothing about where a name ends.
pub fn name_char_ok(i: usize, ch: u8) -> bool {
    ch.is_ascii_alphabetic() || (i > 0 && (ch == b'.' || ch.is_ascii_digit()))
}

/// The `.packonly` manifest that travels with a source tree: the files
/// `build-image` packs into the image verbatim rather than compiling. Everything
/// *not* listed is treated as Oberon source and compiled — so the list is the
/// single, unambiguous record of "don't compile this", which the compiler itself
/// cannot infer (`ORP.Compile` will happily try to parse a font). `build-image`
/// reads it; `extract-source` writes it. Both go through here so the format can't
/// drift.
///
/// Format: one file name per line; blank lines and `#` comments are ignored. A
/// `#` can't occur in an Oberon file name (the set is letters/digits/`.`), so it
/// is an unambiguous comment marker.
pub mod packonly {
    use std::collections::BTreeSet;

    /// Parse `.packonly` text into the set of pack-only file names.
    pub fn parse(text: &str) -> BTreeSet<String> {
        text.lines()
            .map(|line| line.split('#').next().unwrap_or("").trim())
            .filter(|name| !name.is_empty())
            .map(str::to_owned)
            .collect()
    }

    /// Render a `.packonly` file: a fixed explanatory header, then the names
    /// sorted one per line. `parse` ignores the header, so this round-trips.
    pub fn render(names: &BTreeSet<String>) -> String {
        let mut out = String::from(
            "# .packonly — files packed into the image as-is, never compiled.\n\
             # Everything else in this directory is compiled as Oberon source.\n\
             # An empty list compiles everything. Regenerated by extract-source.\n",
        );
        for name in names {
            out.push_str(name);
            out.push('\n');
        }
        out
    }

    #[cfg(test)]
    mod tests {
        use super::{parse, render};
        use std::collections::BTreeSet;

        fn set(names: &[&str]) -> BTreeSet<String> {
            names.iter().copied().map(String::from).collect()
        }

        #[test]
        fn parse_ignores_comments_and_blank_lines() {
            let got = parse("# header\nDisplay.Orig.Mod\n\n  Oberon10.Scn.Fnt  # a font\n");
            assert_eq!(got, set(&["Display.Orig.Mod", "Oberon10.Scn.Fnt"]));
        }

        #[test]
        fn render_round_trips_through_parse() {
            let names = set(&["B.Fnt", "A.Mod"]);
            assert_eq!(parse(&render(&names)), names);
        }

        #[test]
        fn empty_list_renders_and_parses_empty() {
            assert!(parse(&render(&BTreeSet::new())).is_empty());
        }
    }
}

#[cfg(test)]
mod tests {
    use super::name_char_ok;

    #[test]
    fn first_char_must_be_a_letter() {
        assert!(name_char_ok(0, b'K'));
        assert!(!name_char_ok(0, b'9')); // a digit may not lead
        assert!(!name_char_ok(0, b'.')); // nor a dot
    }

    #[test]
    fn later_chars_allow_letters_digits_and_dot() {
        assert!(name_char_ok(6, b'e'));
        assert!(name_char_ok(6, b'.'));
        assert!(name_char_ok(6, b'5'));
    }

    #[test]
    fn path_separators_are_never_legal() {
        assert!(!name_char_ok(0, b'/'));
        assert!(!name_char_ok(6, b'/'));
        assert!(!name_char_ok(6, b'-'));
    }
}
