//! The `.packonly` manifest that travels with a source tree: the files the image
//! builders pack into the image verbatim rather than compiling. Everything *not*
//! listed is treated as Oberon source and compiled — so the list is the single,
//! unambiguous record of "don't compile this", which the compiler itself cannot
//! infer (`ORP.Compile` will happily try to parse a font). [`resolve`](crate::resolve)
//! reads it; `extract-source` writes it. Both go through here so the format can't
//! drift.
//!
//! Format: one file name per line; blank lines and `#` comments are ignored. A `#`
//! can't occur in an Oberon file name (the set is letters/digits/`.`), so it is an
//! unambiguous comment marker.

use std::collections::BTreeSet;

/// Parse `.packonly` text into the set of pack-only file names.
pub fn parse(text: &str) -> BTreeSet<String> {
    text.lines()
        .map(|line| line.split('#').next().unwrap_or("").trim())
        .filter(|name| !name.is_empty())
        .map(str::to_owned)
        .collect()
}

/// Render a `.packonly` file: a fixed explanatory header, then the names sorted one
/// per line. `parse` ignores the header, so this round-trips.
pub fn render(names: &BTreeSet<String>) -> String {
    let mut out = String::from(
        "# .packonly — files packed into the image as-is, never compiled.\n\
         # Everything else in this directory is compiled as Oberon source.\n\
         # An empty list compiles everything. Regenerated by extract-source.\n",
    );
    for name in names {
        out.push_str(name);
        out.push('\n');
    }
    out
}

#[cfg(test)]
mod tests {
    use super::{parse, render};
    use std::collections::BTreeSet;

    fn set(names: &[&str]) -> BTreeSet<String> {
        names.iter().copied().map(String::from).collect()
    }

    #[test]
    fn parse_ignores_comments_and_blank_lines() {
        let got = parse("# header\nDisplay.Orig.Mod\n\n  Oberon10.Scn.Fnt  # a font\n");
        assert_eq!(got, set(&["Display.Orig.Mod", "Oberon10.Scn.Fnt"]));
    }

    #[test]
    fn render_round_trips_through_parse() {
        let names = set(&["B.Fnt", "A.Mod"]);
        assert_eq!(parse(&render(&names)), names);
    }

    #[test]
    fn empty_list_renders_and_parses_empty() {
        assert!(parse(&render(&BTreeSet::new())).is_empty());
    }
}
